"""empty message

Revision ID: d9b2e59079ae
Revises: eb8cef5c646c
Create Date: 2018-03-23 01:40:32.011233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b2e59079ae'
down_revision = 'eb8cef5c646c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('date_created', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'date_created')
    # ### end Alembic commands ###
